language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/reqs-ngstk.txt
  - pip install -r requirements/reqs-test.txt
script: pytest -v --cov=pypiper
after_success:
  - coveralls
branches:
  only:
    - dev
    - master
